### ISSUE TITLE
ilbnetcdf-dev how to install?

### ISSUE THREAD

**Issue by Gxmg** [jllodra/ncdump-json#18]
hello,   libnetcdf-dev this lib how to install  on mac ? please tell me ?thanks!

**Comment by jllodra** [comment]
Hi @Gxmg,

Have you tried using brew?

Quite old issue, but maybe it gives you some hints:

https://github.com/jllodra/ncdump-json/issues/5#issuecomment-138699106

**Comment by Gxmg** [comment]
thanks,I solved the problem。
