### ISSUE TITLE
Did you test on RHEL / Centos

### ISSUE THREAD

**Issue by Akshay-Hegde** [jllodra/ncdump-json#4]
Hi! Did you test on RHEL / Centos, I am on Centos 6.4, I could not build it, any guess what could be wrong ?

[root@localhost ncdump-json-master]# gcc --version
gcc (GCC) 4.8.1 20130715 (Red Hat 4.8.1-4)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@localhost ncdump-json-master]# g++ --version
g++ (GCC) 4.8.1 20130715 (Red Hat 4.8.1-4)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@localhost ncdump-json-master]# make
[ 16%] Building C object CMakeFiles/ncdump-json.dir/src/dumplib.c.o
[ 33%] Building C object CMakeFiles/ncdump-json.dir/src/ncdump.c.o
[ 50%] Building C object CMakeFiles/ncdump-json.dir/src/nctime.c.o
[ 66%] Building C object CMakeFiles/ncdump-json.dir/src/nciter.c.o
[ 83%] Building C object CMakeFiles/ncdump-json.dir/src/indent.c.o
[100%] Building C object CMakeFiles/ncdump-json.dir/src/vardata.c.o
Linking C executable ncdump-json
CMakeFiles/ncdump-json.dir/src/dumplib.c.o: In function `count_udtypes':
dumplib.c:(.text+0xdbd): undefined reference to `nc_inq_typeids'
dumplib.c:(.text+0xdf3): undefined reference to `nc_inq_grps'
dumplib.c:(.text+0xe3b): undefined reference to `nc_inq_grps'
CMakeFiles/ncdump-json.dir/src/dumplib.c.o: In function `ncenum_typ_tostring':
dumplib.c:(.text+0x2040): undefined reference to `nc_inq_enum_ident'
CMakeFiles/ncdump-json.dir/src/dumplib.c.o: In function `nc_inq_gvarid':
dumplib.c:(.text+0x3458): undefined reference to `nc_inq_grpname_full'
dumplib.c:(.text+0x349e): undefined reference to `nc_inq_grpname_full'
CMakeFiles/ncdump-json.dir/src/dumplib.c.o: In function `init_types':
dumplib.c:(.text+0x3808): undefined reference to `nc_inq_typeids'
dumplib.c:(.text+0x385e): undefined reference to `nc_inq_typeids'
dumplib.c:(.text+0x38e6): undefined reference to `nc_inq_user_type'
dumplib.c:(.text+0x3989): undefined reference to `nc_inq_grpname_full'
dumplib.c:(.text+0x39db): undefined reference to `nc_inq_grpname_full'
dumplib.c:(.text+0x3b79): undefined reference to `nc_inq_compound_field'
dumplib.c:(.text+0x3bf4): undefined reference to `nc_inq_compound_field'
dumplib.c:(.text+0x3e26): undefined reference to `nc_inq_grps'
dumplib.c:(.text+0x3e82): undefined reference to `nc_inq_grps'
CMakeFiles/ncdump-json.dir/src/dumplib.c.o: In function `isrecvar':
dumplib.c:(.text+0x415b): undefined reference to `nc_inq_unlimdims'
dumplib.c:(.text+0x41a6): undefined reference to `nc_inq_unlimdims'
CMakeFiles/ncdump-json.dir/src/dumplib.c.o: In function `get_type_name':
dumplib.c:(.text+0x44c7): undefined reference to `nc_inq_user_type'
CMakeFiles/ncdump-json.dir/src/dumplib.c.o: In function `print_type_name':
dumplib.c:(.text+0x45dc): undefined reference to `nc_inq_typeids'
dumplib.c:(.text+0x463d): undefined reference to `nc_inq_typeids'
dumplib.c:(.text+0x4718): undefined reference to `nc_inq_grp_parent'
CMakeFiles/ncdump-json.dir/src/ncdump.c.o: In function `pr_att':
ncdump.c:(.text+0x158b): undefined reference to `nc_free_string'
ncdump.c:(.text+0x15d3): undefined reference to `nc_inq_user_type'
ncdump.c:(.text+0x190e): undefined reference to `nc_inq_enum_ident'
CMakeFiles/ncdump-json.dir/src/ncdump.c.o: In function `pr_att_specials':
ncdump.c:(.text+0x1b07): undefined reference to `nc_inq_var_chunking'
ncdump.c:(.text+0x1bad): undefined reference to `nc_inq_var_chunking'
ncdump.c:(.text+0x1c98): undefined reference to `nc_inq_var_deflate'
ncdump.c:(.text+0x1d2a): undefined reference to `nc_inq_var_fletcher32'
ncdump.c:(.text+0x1da4): undefined reference to `nc_inq_var_endian'
ncdump.c:(.text+0x1e76): undefined reference to `nc_inq_var_fill'
CMakeFiles/ncdump-json.dir/src/ncdump.c.o: In function `print_enum_type':
ncdump.c:(.text+0x23e4): undefined reference to `nc_inq_user_type'
ncdump.c:(.text+0x2520): undefined reference to `nc_inq_enum_member'
CMakeFiles/ncdump-json.dir/src/ncdump.c.o: In function `print_ud_type':
ncdump.c:(.text+0x26f1): undefined reference to `nc_inq_user_type'
ncdump.c:(.text+0x289a): undefined reference to `nc_inq_compound_field'
CMakeFiles/ncdump-json.dir/src/ncdump.c.o: In function `do_ncdump_rec':
ncdump.c:(.text+0x306a): undefined reference to `nc_inq_typeids'
ncdump.c:(.text+0x30e7): undefined reference to `nc_inq_typeids'
ncdump.c:(.text+0x32e0): undefined reference to `nc_inq_dimids'
ncdump.c:(.text+0x331c): undefined reference to `nc_inq_unlimdims'
ncdump.c:(.text+0x3372): undefined reference to `nc_inq_unlimdims'
ncdump.c:(.text+0x4224): undefined reference to `nc_inq_grps'
ncdump.c:(.text+0x4284): undefined reference to `nc_inq_grps'
ncdump.c:(.text+0x42e3): undefined reference to `nc_inq_grpname'
CMakeFiles/ncdump-json.dir/src/ncdump.c.o: In function `nc_inq_varname_count':
ncdump.c:(.text+0x4df4): undefined reference to `nc_inq_grps'
ncdump.c:(.text+0x4e3f): undefined reference to `nc_inq_grps'
CMakeFiles/ncdump-json.dir/src/nciter.c.o: In function `nc_get_iter':
nciter.c:(.text+0x277): undefined reference to `nc_inq_var_chunking'
nciter.c:(.text+0x2c4): undefined reference to `nc_inq_var_chunking'
collect2: error: ld returned 1 exit status
make[2]: *** [ncdump-json] Error 1
make[1]: *** [CMakeFiles/ncdump-json.dir/all] Error 2
make: *** [all] Error 2

**Comment by jllodra** [comment]
No,

just guessing, is libnetcdf-devel installed on your system?

**Comment by Akshay-Hegde** [comment]
Yes

**Comment by jllodra** [comment]
Alright,
I will set up a centos box if I have the time,
then I will get back to you.

**Comment by Akshay-Hegde** [comment]
Thank you, dear ..

**Comment by jllodra** [comment]
Compiling it on Centos 6.4 x86_64 was a piece of cake:

1) http://mazamascience.com/WorkingWithData/?p=1429 (Installing system libraries)
2) https://community.hpcloud.com/article/centos-63-instance-giving-cannot-retrieve-metalink-repository-epel-error (Walkthrough Steps)
3) sudo yum --assumeyes install netcdf
    sudo yum --assumeyes install netcdf-devel
4) sudo yum --assumeyes install cmake
5) download ncdump-json, cd to directory
6) cmake .
7) make

I hope you can get it

**Comment by Akshay-Hegde** [comment]
Thank you so much Jilodra, unfortunately I could not succeed in Centos 6.4 may be library issue of my system, but on Centos 7, with netcdf 4.3.2 I could install successfully.

**Comment by jllodra** [comment]
:+1: :smile:
